apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: nexus-pvc
  namespace: nexus-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
  volumeMode: Filesystem
