kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-volume
  namespace: nexus-dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
